
#DATABASE INFO

DB_HOST='127.0.0.1'
DB_USER='root'
DB_PASSWORD='2019212950'
DB_NAME='annotationDB'

# AWS INFO

AWS_S3_ACCESS_KEY = ''
AWS_S3_SECRET_KEY = ''
AWS_S3_BUCKET_NAME = ''
AWS_S3_LOCATION_NAME = ''

AWS_RDS_HOST  = ''
AWS_RDS_USER = ''
AWS_RDS_PASSWORD = ''
AWS_RDS_DATABASE_NAME = 'annotationDB'